server:
  port: 9001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.23:3306/test?useUnicode=true&characterEncoding=utf8
    username: bdmeasuredata
    password: bdmeasuredata
    initialSize: 3
    maxActive: 100
    minIdle: 10
    maxWait: 5000
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml   # mapper映射文件所在路径
  type-aliases-package: com.cloud.po                    # 所有entity别名类所在包
  config-location: classpath:mybatis/mybatis.cfg.xml    # mapper映射文件所在路径

logging:
  level: info



