server:
  port: 8003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.5.199:3306/springboot3?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    initialSize: 3
    maxActive: 100
    minIdle: 10
    maxWait: 5000
  application:
    name: provider-server
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml   # mapper映射文件所在路径
  type-aliases-package: com.cloud.po                    # 所有entity别名类所在包
  config-location: classpath:mybatis/mybatis.cfg.xml    # mapper映射文件所在路径

logging:
  level: info

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka.com:7001/eureka
  instance:
    instance-id: provider-server:8003                 #自定义服务名称信息
    prefer-ip-address: true                           #访问路径显示IP

info:    #添加actuator依赖，在本地pom或parent pom 中添加  resources 样例查看 springcloud下pom build 配置
  app.name: springcloud-learn
  company.name: www.eurekalearn.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"